title: "Foxy Scholar"
description: "Foxyhyun의 논문 리뷰 & 연구 노트"
author: "Sihyun Lee"
url: "https://foxyhyun.github.io"

remote_theme: pages-themes/slate@v0.2.0   # 유지 (방법 B)

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/

defaults:
  - scope:
      path: ""       
      type: posts
    values:
      layout: post              # 기본 포스트는 post.html 적용
      categories: ["PaperReview"]

  - scope:
      path: ""
      type: tutorials
    values:
      layout: post
      categories: ["Tutorial"]

include:
  - _pages
  - assets
future: true

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
mathjax: true


