title: "Foxy Scholar"
description: "Foxyhyun의 논문 리뷰 & 연구 노트"
author: "Sihyun Lee"
url: "https://foxyhyun.github.io"

# 테마는 유지해도 되지만, 우리는 커스텀 레이아웃을 쓰므로
# visual은 주로 /assets/style.css 로 제어됩니다.
remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# 포스트 기본값 (모든 리뷰가 PaperReview 카테고리에 들어가도록)
# _config.yml
defaults:
  - scope:
      path: ""       # 모든 posts
      type: posts
    values:
      layout: default          # ← post 말고 default 사용
      categories: ["PaperReview"]   # 필요 시 유지

# Jekyll이 기본적으로 무시하는 폴더 포함
include:
  - _pages
  - assets
future: true

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
