title: "Foxy Scholar"
description: "Foxyhyun의 논문 리뷰 & 연구 노트"
author: "Sihyun Lee"
url: "https://foxyhyun.github.io"

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      categories: ["review"]

navbar:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Categories
    link: /categories/
  - name: Tags
    link: /tags/
  - name: Blog
    link: /blog/